include:
  - board: nice_nano//zmk
    shield: totem_max_left
    artifact-name: totem_max_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  - board: nice_nano//zmk
    shield: totem_max_right
    artifact-name: totem_max_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  - board: xiao_ble//zmk
    shield: totem_max_dongle prospector_adapter
    artifact-name: totem_max_dongle_prospector
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: nice_nano//zmk
    shield: settings_reset
    artifact-name: settings_reset_nice_nano

  - board: xiao_ble//zmk
    shield: settings_reset
    artifact-name: settings_reset_xiao_ble
