# This file generates the GitHub Actions matrix
include:
  - board: nice_nano_v2
    shield: totem_max_left
  - board: nice_nano_v2
    shield: totem_max_right
  - board: seeeduino_xiao_ble
    shield: totem_max_dongle prospector_adapter
